### ISSUE TITLE
Can this driver library be driven by spi

### ISSUE THREAD

**Issue by LNqueen** [masoud-babaabasi/W25N01-flash-library#1]
I have a project that needs to use spi driver w25n01 and mount fatfs, but I have not found a suitable driver. Most of this driver library meets my requirements, but I don't know whether it supports spi drivers.

**Comment by masoud-babaabasi** [comment]
Hi, this library can not be used via SPI. I have added another library that is specifically written to support SPI driver. I hope that this new library meets your project's requirements.

**Comment by LNqueen** [comment]
Thank you very much!! let me try it.

**Comment by masoud-babaabasi** [comment]
If you need only one chip, you can manipulate the library to use only one chip.

**Comment by LNqueen** [comment]
okay :)

**Comment by LNqueen** [comment]
thank you, it worked!
