### ISSUE TITLE
f_sync strange behaviour

### ISSUE THREAD

**Issue by simon88** [masoud-babaabasi/W25N01-flash-library#3]
first of all thank you for your library I use it with spi 👍 . 
But I have strange behavior when I do f_sync, if I do for example something like this : 
````
   // before I've formated and mount file system
   //I opend the file with f_open

    const char *data1 = "First\n";
    res = f_write(&file, data1, strlen(data1), &bw);

    f_sync(&file);

    const char *data2 = "Second\n";
    res = f_write(&file, data2, strlen(data2), &bw);
    f_sync(&file);

````

If I had a print in `DRESULT USER_write ` just before `W25NXX_Write`to print `buff`I have a strange behaviour.

After first call of `f_sync`I print `First\n.`, but after second call to f_sync I print `First\nSecond\n`here is the strange behaviour because second call to f_sync will normally only print Second\n... 
Is it normal or not? Maybe I miss or misunderstood something...

I've modified the library to work with only one w25n01 chip

**Comment by masoud-babaabasi** [comment]
Hi, I'm not sure about your issue, but I think it is about how you open the file in write mode. You can use f_lseek to move the pointer to the end of the file.
